name: Automated Database Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Diariamente a las 2 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and run backup
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto
            
            # Hacer scripts ejecutables
            chmod +x scripts/*.sh
            
            # Ejecutar backup CON DOCKER (sin docker-compose)
            DB_HOST="${{ secrets.DB_HOST }}" \
            DB_PORT="${{ secrets.DB_PORT }}" \
            DB_USER="${{ secrets.DB_USER }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            DB_NAME="${{ secrets.DB_NAME }}" \
            ./scripts/backup-docker.sh
            
            echo "✅ Backup automatizado completado"